### ISSUE TITLE
Some images missing on tutorial pages

### ISSUE THREAD

**Issue by andyb1979** [ABTSoftware/SciChart.Android.Documentation#1]
For example
https://www.scichart.com/documentation/android/latest/articles/quickStartGuide/tutorials2d/Tutorial%2002%20-%20Zooming%20and%20Panning%20Behavior.html?tabs=java

https://www.scichart.com/documentation/android/latest/articles/quickStartGuide/tutorials2d/Tutorial%2004%20-%20Adding%20Realtime%20Updates.html?tabs=java

https://www.scichart.com/documentation/android/latest/articles/quickStartGuide/tutorials2d/Tutorial%2005%20-%20Annotations.html?tabs=java

https://www.scichart.com/documentation/android/latest/articles/quickStartGuide/tutorials2d/Tutorial%2006%20-%20Multiple%20Axis.html?tabs=java

all have missing images

Is there a way to check for missing images or links?

**Comment by andriypohorilko** [comment]
Use HTML video tag for videos since markdown doesn't support mp4 videos in Chrome
