### ISSUE TITLE
Missing some documentation topics 

### ISSUE THREAD

**Issue by andyb1979** [ABTSoftware/SciChart.Android.Documentation#2]
I may be mistaken / cannot find them but the following topics appear to be missing

1. Viewport manager (old doc https://www.scichart.com/documentation/android/current/webframe.html#ViewportManager%20-%20Full%20Control%20over%20Axis%20Ranges%20and%20Viewport.html ) 
2. Renderer plugins https://www.scichart.com/documentation/android/current/webframe.html#Renderer%20Plugins.html
3. RenderContext API https://www.scichart.com/documentation/android/current/webframe.html#RenderContext%20API.html
4. Export chart to Bitmap https://www.scichart.com/documentation/android/current/webframe.html#Export%20Chart%20to%20Bitmap.html
5. Suspending updates https://www.scichart.com/documentation/android/current/webframe.html#Suspending%20Updates%20of%20Chart.html
6. SciChartOverview (not present in old or new docs)

**Comment by andriypohorilko** [comment]
I've added articles 1-5.
We don't have SciChartOverview on Mobile yet.
